In [1]:
import numpy as np 
import pandas as pd 
from sklearn.neighbors import KNeighborsClassifier

In [3]:
train_data = pd.read_csv('data.csv', delimiter=',', index_col='id')

In [6]:
x_train = pd.DataFrame(train_data.drop(['Class'], axis=1))
y_train = train_data['Class']

In [7]:
knn = KNeighborsClassifier(n_neighbors=3, p=2) # evclid
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [8]:
new_object = [17, 94]

In [16]:
knn.kneighbors([new_object])

(array([[11.18033989, 29.42787794, 40.80441153]]),
 array([[9, 8, 0]], dtype=int64))

In [18]:
knn.predict([new_object])

array([1], dtype=int64)

In [19]:
knn.predict_proba([new_object])

array([[0.33333333, 0.66666667]])

In [21]:
knn = KNeighborsClassifier(n_neighbors=3, p=1) # manheten
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3, p=1)

In [22]:
knn.kneighbors([new_object])

(array([[13., 34., 51.]]), array([[9, 8, 0]], dtype=int64))