In [6]:
import numpy as np 
import pandas as pd 
from sklearn.linear_model import LinearRegression

In [7]:
data = pd.read_csv('candy-data.csv', index_col='competitorname')
data.head()

chocolate  fruity  caramel  peanutyalmondy  nougat  \
competitorname                                                       
100 Grand               1       0        1               0       0   
3 Musketeers            1       0        0               0       1   
One dime                0       0        0               0       0   
One quarter             0       0        0               0       0   
Air Heads               0       1        0               0       0   

                crispedricewafer  hard  bar  pluribus  sugarpercent  \
competitorname                                                        
100 Grand                      1     0    1         0         0.732   
3 Musketeers                   0     0    1         0         0.604   
One dime                       0     0    0         0         0.011   
One quarter                    0     0    0         0         0.011   
Air Heads                      0     0    0         0         0.906   

                pricepercent  winpercent  Y  
competitorname                               
100 Grand              0.860   66.971725  1  
3 Musketeers           0.511   67.602936  1  
One dime               0.116   32.261086  0  
One quarter            0.511   46.116505  0  
Air Heads              0.511   52.341465  1

In [11]:
train_data = data[(data.index != 'One dime') & (data.index != 'Nestle Butterfinger')]#pd.DataFrame(data.drop(['winpercent', 'Y'], axis=1))
one_dime = pd.DataFrame(data[data.index == 'One dime'].drop(['winpercent', 'Y'], axis=1))
nestle = pd.DataFrame(data[data.index == 'Nestle Butterfinger'].drop(['winpercent', 'Y'], axis=1))

In [12]:
x_train = pd.DataFrame(train_data.drop(['winpercent', 'Y'], axis=1))
y_train = train_data['winpercent']

In [13]:
regression = LinearRegression()
regression.fit(x_train, y_train)

LinearRegression()

In [16]:
regression.predict(one_dime)

array([36.63093922])

In [23]:
regression.predict(nestle)

array([62.8766418])

In [19]:
regression.predict([[0, 1, 1, 1, 1, 1, 1, 0, 1, 0.26, 0.296]])

array([57.51458634])